line-length = 100
target-version = "py310"
exclude = [
    "PDFdump.py",
    "TestBP.xlsx",
    "README.pdf",
    "Liste BP Cleaning Kreditoren.xlsx",
]

[lint]
select = ["E", "F", "I", "B", "UP", "ANN"]
ignore = [
    "ANN101",
    "ANN102",
    "ANN401",
]

[lint.per-file-ignores]
"tests/*" = ["ANN", "UP031"]
"tests/test_handelsregister.py" = ["E501"]
"src/bpauto/handelsregister.py" = ["ANN", "E501"]
"src/bpauto/pdf_scanner.py" = ["ANN", "E501"]
